import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const results=[]; const add=(name,ok,detail='')=>{results.push({name,ok:Boolean(ok),detail:String(detail||'')});if(!ok)process.exitCode=1;};
const manifest=JSON.parse(fs.readFileSync(path.join(root,'assets/ASSET_MANIFEST.json'),'utf8'));
const build=JSON.parse(fs.readFileSync(path.join(root,'BUILD_INFO.json'),'utf8'));
const sandbox={console,encodeURIComponent,decodeURIComponent,Date,Map,Set};sandbox.globalThis=sandbox;sandbox.window=sandbox;
vm.createContext(sandbox);
for(const rel of ['data/asset-catalog.js','src/core/asset-registry.js']) vm.runInContext(fs.readFileSync(path.join(root,rel),'utf8'),sandbox,{filename:rel});
const registry=sandbox.F1M_CORE.assets.createRegistry({catalog:sandbox.F1M_ASSET_CATALOG,roots:['assets/']});
const snap=registry.snapshot();
add('catalog:build',snap.buildCode===build.build_code,snap.buildCode);
add('catalog:version',snap.manifestVersion===build.assets_manifest,String(snap.manifestVersion));
add('catalog:entry-count',snap.counts.catalogued===manifest.entries.length,String(snap.counts.catalogued));
add('catalog:519-paths',snap.counts.catalogued===519,String(snap.counts.catalogued));
add('catalog:runtime-count',snap.counts.runtimeReferenced===168,String(snap.counts.runtimeReferenced));
add('catalog:required-missing',snap.counts.originalMissingRequired===7,String(snap.counts.originalMissingRequired));
add('catalog:no-case-collisions',snap.counts.caseCollisions===0,String(snap.counts.caseCollisions));
add('path:relative-normalized',registry.normalizePath('flags/all/br.png')==='assets/flags/all/br.png');
add('path:assets-preserved',registry.normalizePath('./assets/teams/logos/ferrari.png')==='assets/teams/logos/ferrari.png');
add('path:traversal-rejected',registry.normalizePath('../secret.png')==='');
add('path:backslash-normalized',registry.normalizePath('assets\\flags\\all\\br.png')==='assets/flags/all/br.png');
add('path:candidate',registry.candidates('flags/all/br.png')[0]==='assets/flags/all/br.png',registry.candidates('flags/all/br.png')[0]);
add('placeholder:data-uri',registry.placeholderDataUri('assets/drivers/current_grid/max_verstappen.png',{label:'MV'}).startsWith('data:image/svg+xml'),registry.placeholderDataUri('x').slice(0,30));
add('type:background',registry.classify('assets/backgrounds/ui/global_lobby.png')==='background');
add('type:avatar',registry.classify('assets/drivers/current_grid/max_verstappen.png')==='avatar');
add('type:logo',registry.classify('assets/teams/logos/ferrari.png')==='logo');
add('type:track',registry.classify('assets/tracks/svg/miami.svg')==='track');
add('metadata:hash',registry.metadata('assets/teams/logos/ferrari.png')?.original_sha256?.length===64);
add('missing:list-seven',snap.missingRequired.length===7,snap.missingRequired.join(','));
const allowed=new Set(['.txt','.json','.md']);
const walk=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>{const f=path.join(dir,e.name);return e.isDirectory()?walk(f):[f];});
const binaries=walk(path.join(root,'assets')).filter(file=>!allowed.has(path.extname(file).toLowerCase()));
add('delivery:no-asset-binaries',binaries.length===0,binaries.map(file=>path.relative(root,file)).join(','));
const catalogSource=fs.readFileSync(path.join(root,'data/asset-catalog.js'),'utf8');
add('catalog:generated-runtime',catalogSource.includes('F1M_ASSET_CATALOG')&&catalogSource.includes(build.build_code));
const script=fs.readFileSync(path.join(root,'script.js'),'utf8');
add('integration:registry-created',script.includes('CORE.assets?.createRegistry'));
add('integration:hydrate-delegated',script.includes('assetRegistry.hydrate'));
add('integration:diagnostics-context',script.includes('eventBus:appEvents, assetRegistry'));
const report={build:build.build_code,generatedAt:new Date().toISOString(),passed:results.filter(r=>r.ok).length,failed:results.filter(r=>!r.ok).length,results};
fs.writeFileSync(path.join(root,'test-results/assets-audit.json'),JSON.stringify(report,null,2)+'\n');
console.log(results.map(r=>`${r.ok?'PASS':'FAIL'} ${r.name}${r.detail?' — '+r.detail:''}`).join('\n'));
console.log(`TOTAL: ${report.passed} passed, ${report.failed} failed`);
