import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const results=[]; const add=(name,ok,detail='')=>{results.push({name,ok:Boolean(ok),detail:String(detail||'')}); if(!ok) process.exitCode=1;};
const build=JSON.parse(fs.readFileSync(path.join(root,'BUILD_INFO.json'),'utf8'));
const sandbox={console,Date,JSON,Math}; sandbox.globalThis=sandbox; sandbox.window=sandbox;
vm.createContext(sandbox);
for(const rel of ['data/regulation-data.js','src/core/regulation-engine.js','data/sporting-data.js','src/core/sporting-database.js']) vm.runInContext(fs.readFileSync(path.join(root,rel),'utf8'),sandbox,{filename:rel});
const engine=sandbox.F1M_CORE.regulations.createRegulationEngine({data:sandbox.F1M_REGULATION_DATA});
const audit=engine.audit();
add('build:phase-at-least-10', Number(build.phase)>=10, String(build.phase));
add('data:schema-1', Number(sandbox.F1M_REGULATION_DATA.schema)===1, String(sandbox.F1M_REGULATION_DATA.schema));
const f1=engine.activeSessionPlan('F1',{id:'australia'});
const sprint=engine.activeSessionPlan('F1',{id:'brazil', sprint:true});
const f2=engine.activeSessionPlan('F2',{id:'melbourne'});
add('f1:grand-prix-q1-q2-q3', ['q1','q2','q3'].every(id=>f1.sessions.some(s=>s.id===id)), f1.sessions.map(s=>s.id).join(','));
add('f1:sprint-format', sprint.sessions.some(s=>s.id==='sprint') && sprint.sessions.some(s=>s.id==='sprintQualifying'), sprint.sessions.map(s=>s.id).join(','));
add('f2:sprint-feature', f2.sessions.some(s=>s.id==='sprint') && f2.sessions.some(s=>s.id==='feature'), f2.sessions.map(s=>s.id).join(','));
add('f2:reverse-grid-top10', f2.sessions.find(s=>s.id==='sprint')?.reverseGridTop===10, String(f2.sessions.find(s=>s.id==='sprint')?.reverseGridTop));
add('points:f1-race-winner-25', engine.pointsForPosition(1,{series:'F1',eventType:'race'})===25, String(engine.pointsForPosition(1,{series:'F1',eventType:'race'})));
add('points:f1-sprint-winner-8', engine.pointsForPosition(1,{series:'F1',eventType:'sprint'})===8, String(engine.pointsForPosition(1,{series:'F1',eventType:'sprint'})));
add('points:f2-sprint-winner-10', engine.pointsForPosition(1,{series:'F2',eventType:'sprint'})===10, String(engine.pointsForPosition(1,{series:'F2',eventType:'sprint'})));
add('points:f2-feature-winner-25', engine.pointsForPosition(1,{series:'F2',eventType:'feature'})===25, String(engine.pointsForPosition(1,{series:'F2',eventType:'feature'})));
add('points:f2-pole-2', engine.pointsForPosition(99,{series:'F2',pole:true})===2, String(engine.pointsForPosition(99,{series:'F2',pole:true})));
const sample=Array.from({length:22},(_,i)=>({driver:'D'+i,team:'T'+i,score:100-i,time:String(80+i/10)}));
const q=engine.simulateQualifyingStages(sample,{series:'F1'});
add('qualifying:f1-22-classified', q.length===22, String(q.length));
add('qualifying:f1-q3-top10', q.slice(0,10).every(r=>r.qStage==='Q3'), q.slice(0,10).map(r=>r.qStage).join(','));
const f2q=engine.simulateQualifyingStages(sample,{series:'F2'});
const f2Sprint=engine.sprintGridFromQualifying(f2q,'F2');
add('qualifying:f2-single-stage', f2q.every(r=>r.qStage==='F2-Q'), f2q[0]?.qStage);
add('sprint:f2-top10-reversed', f2Sprint[0].driver===f2q[9].driver && f2Sprint[9].driver===f2q[0].driver, `${f2Sprint[0].driver}/${f2Sprint[9].driver}`);
const classified=engine.classifyRace([{driver:{short:'A'},team:{id:'t'},distance:10,totalTime:100,penalties:[]},{driver:{short:'B'},team:{id:'t'},distance:10,totalTime:98,penalties:['causingCollision']}],{series:'F1'});
add('classification:penalty-applied', classified[0].driver==='A' && classified[1].penaltySeconds===10, JSON.stringify(classified));
add('audit:internal-pass', audit.failed===0, `${audit.passed}/${audit.failed}`);
const report={build:build.build_code,generatedAt:new Date().toISOString(),passed:results.filter(r=>r.ok).length,failed:results.filter(r=>!r.ok).length,results,audit};
fs.writeFileSync(path.join(root,'test-results/regulation-audit.json'),JSON.stringify(report,null,2)+'\n');
console.log(results.map(r=>`${r.ok?'PASS':'FAIL'} ${r.name}${r.detail?' — '+r.detail:''}`).join('\n'));
console.log(`TOTAL: ${report.passed} passed, ${report.failed} failed`);
