import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const results=[]; const add=(name,ok,detail='')=>{results.push({name,ok:Boolean(ok),detail}); if(!ok) process.exitCode=1;};
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
for(const rel of ['data/telemetry-data.js','src/core/telemetry-system.js']){
  try{ new vm.Script(read(rel),{filename:rel}); add(`syntax:${rel}`,true); } catch(error){ add(`syntax:${rel}`,false,error.message); }
}
const sandbox = { globalThis:{}, window:{}, console };
sandbox.globalThis = sandbox; sandbox.window = sandbox;
vm.createContext(sandbox);
vm.runInContext(read('data/telemetry-data.js'), sandbox);
vm.runInContext(read('src/core/telemetry-system.js'), sandbox);
const api = sandbox.F1M_CORE?.telemetry?.createTelemetrySystem?.({ data:sandbox.F1M_TELEMETRY_DATA });
const state = { saveSchema:25, quality:{}, telemetry:{} };
api?.initializeState?.(state, { buildCode:'TEST-F25' });
const race = { tick:12, weather:'dry', trackState:{ grip:.98 }, trackInfo:{ name:'Telemetry Test GP' }, entries:[] };
const entry = { driver:{short:'SIM'}, team:{id:'test'}, baseSpeed:.019, tyre:38, condition:86, ers:12, gap:.6, pace:'attack', lap:10, sector:3, fuel:76, brakeTemp:940, engineTemp:100, progress:9.83 };
const packet = api?.sample?.(entry, race, { state, traffic:{dirtyAir:.91}, buildCode:'TEST-F25' });
entry.telemetry = packet;
const diagnosis = api?.diagnose?.(entry, race, { state, sample:packet, buildCode:'TEST-F25' });
const trace = api?.sectorTrace?.(entry, race, { state, sample:packet });
const exportSession = api?.exportSession?.(state, race, { buildCode:'TEST-F25' });
const audit = api?.audit?.({ state, buildCode:'TEST-F25' });
const status = api?.status?.(state, { buildCode:'TEST-F25' });
add('f25:data-loaded', Number(sandbox.F1M_TELEMETRY_DATA?.phase) === 25, 'phase '+sandbox.F1M_TELEMETRY_DATA?.phase);
add('f25:core-api', Boolean(api?.initializeState && api?.sample && api?.diagnose && api?.sectorTrace && api?.exportSession && api?.audit), 'api completa');
add('f25:packet-speed-rpm', Number(packet?.speedKph || 0) >= 60 && Number(packet?.rpm || 0) >= 6500, JSON.stringify(packet || {}));
add('f25:thermal-tyres-brakes', Number(packet?.tyreSurfaceC || 0) >= 70 && Number(packet?.brakeTempC || 0) >= 320, `${packet?.tyreSurfaceC}/${packet?.brakeTempC}`);
add('f25:diagnosis', Boolean(diagnosis?.top?.label) && Number(diagnosis?.priority || 0) > 0, JSON.stringify(diagnosis || {}));
add('f25:sector-trace', Array.isArray(trace) && trace.length === 3 && trace.every(s=>Number.isFinite(s.delta)), JSON.stringify(trace || []));
add('f25:export-session', exportSession?.format === 'F1M_TELEMETRY_SESSION_V1' && exportSession.samples?.length >= 1, JSON.stringify(exportSession || {}));
add('f25:audit-score', Number(audit?.score || 0) >= 100 && Number(audit?.failed ?? 1) === 0, `${audit?.score || 0}/100`);
add('f25:status', status?.productionBlocked === true && status?.signals >= 17 && status?.diagnosis >= 7, JSON.stringify(status || {}));
const index=read('index.html'); const script=read('script.js'); const pkg=JSON.parse(read('package.json')); const css=read('style.css'); const career=read('src/systems/career-system.js');
add('index:scripts', index.includes('data/telemetry-data.js') && index.includes('src/core/telemetry-system.js'), 'scripts F25');
add('script:system-card', script.includes('telemetryMiniHTML') && script.includes('runTelemetryAudit') && script.includes('exportTelemetrySession') && script.includes('runTelemetryDiagnosis'), 'central sistema');
add('script:state-init', script.includes('telemetrySystem?.initializeState') && script.includes('state.telemetry'), 'state init');
add('script:race-hooks', script.includes('telemetrySystem?.sample') && script.includes('telemetryLine') && script.includes('engineerDiagnosis'), 'race hooks');
add('script:actions', script.includes('runTelemetryAudit(){ runTelemetryAudit(); }') && script.includes('exportTelemetrySession(){ exportTelemetrySession(); }'), 'actions');
add('career:schema25', career.includes('if(current < 25') && career.includes('telemetryF25'), 'schema 25');
add('css:f25', css.includes('telemetry-card') && css.includes('F25'), 'css F25');
add('package:script', Boolean(pkg.scripts?.['test:telemetry']), 'test:telemetry');
add('docs:guide', fs.existsSync(path.join(root,'docs/TELEMETRY_SIMULATOR_F25.md')), 'guide F25');
const summary={build:JSON.parse(read('BUILD_INFO.json')).build_code, generatedAt:new Date().toISOString(), passed:results.filter(r=>r.ok).length, failed:results.filter(r=>!r.ok).length, results};
fs.mkdirSync(path.join(root,'test-results'),{recursive:true});
fs.writeFileSync(path.join(root,'test-results/telemetry-audit.json'),JSON.stringify(summary,null,2)+'\n');
console.log(results.map(r=>`${r.ok?'PASS':'FAIL'} ${r.name}${r.detail?' — '+r.detail:''}`).join('\n'));
console.log(`TOTAL: ${summary.passed} passed, ${summary.failed} failed`);
